Base code for Android support for Home Edge
lf-edge/edge-home-orchestration-android pull request #1
Opened 2022-09-26 09:03 UTC by suresh-lc

Adding base code for Android support for Home Edge.

Features supported:
1. Device discovery
2. Service discovery
3. Service offload

Signed-off-by: suresh-lc <suresh.lc@samsung.com>

2022-09-26 09:14 UTC, t25kim approved these changes
Wonderful! Thank you for the great contribution!!

2022-09-26 09:37 UTC, t25kim commented
@suresh-lc What about excluding `.idea` folder if it's inessential?

2022-09-26 09:52 UTC, MoonkiHong reviewed
Please take a look at my comments.

2022-09-26 09:52 UTC, MoonkiHong commented on README.md
> +As an continous process to support Home Edge (Linux) to multiple platforms, this project caters to support Home Edge for Android. There are various smart home devices and Android has been making its
```suggestion
As a continous process to support Home Edge (Linux) to multiple platforms, this project caters to support Home Edge for Android. There are various smart home devices and Android has been making its presence in many of these devices. The most essential part of the ecosystem has been Smart phone and specifically Android based smart phones. There are large number of applications developed to support user needs across various domains. Some of the service applications would need compute intensive or containerized applications which are not available on the Android phones. This project helps the service applications on the android phones to leverage on the service offered by devices in the same network.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/androidTest/java/org/lfedge/homeedge/ExampleInstrumentedTest.java
> +package org.lfedge.homeedge;
Copyright statement is required.

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/HomeEdgeService.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/MainActivity.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/NsdHelper.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/client/APIImpl.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/client/APIListener.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/client/Api.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/client/Client.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/client/Response.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/common/Utils.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/database/DeviceDao.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/database/DeviceDatabase.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/model/Device.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/model/ListConverter.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/orchestrationapi/ExternalHandler.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/orchestrationapi/InternalHandler.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/server/HTTPServer.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/main/java/org/lfedge/homeedge/server/ServiceInfo.java
> + Copyright 2022-2023 Samsung Electronics All Rights Reserved.
```suggestion
 Copyright 2022 Samsung Electronics All Rights Reserved.
```

2022-09-26 09:52 UTC, MoonkiHong commented on app/src/test/java/org/lfedge/homeedge/ExampleUnitTest.java
> +package org.lfedge.homeedge;
Copyright statement is required.

2022-09-26 10:17 UTC, MoonkiHong reviewed
PTAL. 😄

2022-09-26 10:17 UTC, MoonkiHong commented on README.md
> +As a continous process to support Home Edge (Linux) to multiple platforms, this project caters to support Home Edge for Android. There are various smart home devices and Android has been making its p
```suggestion
As a continuous process to support Home Edge (Linux) to multiple platforms, this project caters to support Home Edge for Android. There are various smart home devices and Android has been making its presence in many of these devices. The most essential part of the ecosystem has been Smart phone and specifically Android based smart phones. There are large number of applications developed to support user needs across various domains. Some of the service applications would need compute intensive or containerized applications which are not available on the Android phones. This project helps the service applications on the android phones to leverage on the service offered by devices in the same network.
```

2022-09-26 10:17 UTC, MoonkiHong commented on README.md
> +If you want to contribute to the Edge Orchestration project and make it better, your help is very welcome. Contributing is also a great way to learn more about social coding on Github, new technologi
```suggestion
If you want to contribute to the Edge Orchestration project and make it better, your help is very welcome. Contributing is also a great way to learn more about social coding on GitHub, new technologies and their ecosystems.
```

2022-09-26 11:42 UTC, t25kim requested changes
https://github.com/lf-edge/edge-home-orchestration-android/pull/1/commits/dfb6db74ac503c5c7257dff30ea8004f5828410c makes weird.

2022-09-26 11:49 UTC, suresh-lc commented
> [dfb6db7](https://github.com/lf-edge/edge-home-orchestration-android/commit/dfb6db74ac503c5c7257dff30ea8004f5828410c) makes weird.

Hope fine now

2022-09-26 22:50 UTC, t25kim approved these changes

2022-09-27 00:26 UTC, MoonkiHong approved these changes
+1

2022-09-27 07:02 UTC, tdrozdovsky approved these changes
Great first step!

2022-09-27 08:12 UTC, merged